version: "3"

services:

  dizzy-brawl-postgres:
    container_name: dizzy-brawl-postgres
    image: postgres:9.6.20-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=dizzy-brawl
      - POSTGRES_USER=dizzy-brawl
      - POSTGRES_PASSWORD=dizzy-brawl

  dizzy-brawl-backend:
    container_name: dizzy-brawl-backend
    image: dizzy-brawl-backend:v1
    build: .
    ports:
      - 8080:8080
    environment:
      - server.context.path=/api/v1 # context path for endpoints
      - server.ip.v4=0.0.0.0
      - server.port=8080
      - server.workers.pool.count=1 # number of http server's thread-workers
      - database.host=dizzy-brawl-postgres # container name or remote hostname
      - database.port=none # [none]|[some_port] (none - not needed, for example at docker network)
      - database.name=dizzy-brawl
      - database.username=dizzy-brawl
      - database.password=dizzy-brawl
      - database.connection.pool.count=1 # number of simultaneously possible connections with database
      - database.jdbc.driverClassName=org.postgresql.Driver
      - database.url=jdbc:postgresql://dizzy-brawl-postgres/dizzy-brawl # jdbc:<database>://(<hostname>:<port>)|<container_name>]/<database_name>
      - hibernate.dialect=org.hibernate.dialect.PostgreSQL82Dialect
      - hibernate.show_sql=true # for debug mode
      - hibernate.hbm2ddl.auto=create # hibernate entities generation strategy
    links:
      - dizzy-brawl-postgres
    depends_on:
      - dizzy-brawl-postgres
