{
 "title": "Meta Server Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Meta-Server Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"web-server\"}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(vertx_http_server_requestCount_total{job=\"web-server\"})"
    }
   ]
  },
  {
   "title": "Total Successful Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(vertx_http_server_requestCount_total{code=~\"2..\", job=\"web-server\"})"
    }
   ]
  },
  {
   "title": "Total Error Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vertx_http_server_requestCount_total{code=~\"5..\", job=\"web-server\"}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(vertx_http_server_responseTime_seconds_sum{code=~\"...\", job=\"web-server\"}[1m]) / rate(vertx_http_server_responseTime_seconds_count{code=~\"...\", job=\"web-server\"}[1m])"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Available CPUs Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "system_cpu_count{job=\"web-server\"}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"web-server\"}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"web-server\"}"
    }
   ]
  }
 ]
}